baseurl = "https://javierjimenez2.github.io/jjrblog/"
languageCode = "es"
defaultContentLanguage = "en"
theme = "papermod"
paginate = 5

[params]
  contentTypeName = "post"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = true
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  readingTime = true

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.es]
    languageName = "Español"
    title = "JJR Blog"
    [languages.es.params]
      subtitle = "Blog de un pensador que desarrolla"
      owner = ""
      keywords = ["blog", "development", "technology"]
      copyright = ""
      menuMore = "Mostrar más"
      readMore = "Leer más"
      readOtherPosts = "Leer otras entradas"
      newerPosts = "Entradas más recientes"
      olderPosts = "Entradas anteriores"
      missingContentMessage = "Página no encontrada..."
      missingBackButtonLabel = "Volver al inicio"
      minuteReadingTime = "min de lectura"
      words = "palabras"

      [languages.es.params.logo]
        logoText = "JJR Blog"
        logoHomeLink = "/"

      [languages.es.menu]
        [[languages.es.menu.main]]
          identifier = "about"
          name = "Acerca de"
          url = "/about"
  
  [languages.en]
    languageName = "English"
    title = "JJR Blog"
    [languages.en.params]
      subtitle = "A thinker’s blog"
      owner = "Javier Jiménez"
      keywords = ["blog", "development", "technology"]
      copyright = "All rights reserved"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "JJR Blog"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
